version: 2

sources:
    - name: staging
      database: weather-project-92881

      schema: weather_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: kl_historical_partitioned_table
        - name: kl_recent_partitioned_table
         # freshness:
           # error_after: {count: 6, period: hour}